//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/SwoleScript/Source-Unity/Input/DefaultSwoleControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Swole.Unity.InputSystem
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/SwoleScript/Source-Unity/Input/DefaultSwoleControls.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @DefaultSwoleControls: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @DefaultSwoleControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultSwoleControls"",
    ""maps"": [
        {
            ""name"": ""Standard"",
            ""id"": ""f39f3f79-c796-4350-923b-1c71b8c614a7"",
            ""actions"": [
                {
                    ""name"": ""LeftJoystickHorizontal"",
                    ""type"": ""Value"",
                    ""id"": ""ddaa5589-4c4c-4b15-9fd6-65decda70c42"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftJoystickVertical"",
                    ""type"": ""Value"",
                    ""id"": ""22c99de9-0bd9-4286-b927-398b592e9032"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightJoystickHorizontal"",
                    ""type"": ""Value"",
                    ""id"": ""2009e49b-c263-42c4-aeab-b99f5204ecc6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightJoystickVertical"",
                    ""type"": ""Value"",
                    ""id"": ""c2eb6e75-a8ad-406b-acd7-72bbf2e3ed62"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftBumper"",
                    ""type"": ""Button"",
                    ""id"": ""3fb8bb3c-b7c4-42e6-b5b1-064719cefd07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightBumper"",
                    ""type"": ""Button"",
                    ""id"": ""e9cb2cab-feaa-4c2c-acfe-562e276ed393"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorInput"",
                    ""type"": ""Value"",
                    ""id"": ""eb79c71b-aec1-43b6-94c8-48bc4d0d356d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""8fc75f53-e01c-43d5-8ca4-dc0ade1f34f2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""7c40ff31-16d1-47b8-8084-27d23f8c8d24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""0bf7aaec-6a66-42e1-b441-581878fe4c7a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""7f8df1f6-ee0a-4ec3-9540-57f3a9cf8e0d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""a4a56850-2e54-4b19-97ab-520291d0f28d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""25399513-9628-4bb4-8f28-f5a8456fc2d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""36719321-510f-4411-ac96-4ade80910a70"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftJoystickHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96f1779d-17a9-419b-9f1b-345fa9f84687"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftJoystickVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3979dd07-b1af-4eb3-949e-d8428c27153c"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightJoystickHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""391d7af1-3476-4b50-901e-ea56c567bffe"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightJoystickVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cee3ea22-128c-4c28-9020-2d7b42a9b036"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f41145d-3bd7-4139-a931-f0dcdfe79996"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""625f5b9e-6841-4bfb-ba21-9528e74de384"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CursorInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78c41d77-48c1-4136-8353-57e08855f45c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92dde0e5-cc59-422b-8f89-307caeae4dae"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a519c65-bfe8-458b-a29d-3486cafbe642"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ef454e3-76a4-4bfe-97b0-71b4e675b0ca"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dcedcfc-765a-4875-bfb9-47cbd6aa2227"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88021601-38bf-4a0d-9c8f-48af3d0a2da8"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87e19187-54c8-464d-b8f4-c5a615e7500c"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""416ab9be-5b30-49a6-81f8-ace815eabeb4"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e69f4c4-4d7f-456f-9cc1-481ccf492619"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d229aded-766f-49a0-a684-b74cca38e2e8"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3ec8936-fbe2-4c52-8f51-3d9455f96897"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0a2d494-ee15-495b-aef2-61419b7e171f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MOBA"",
            ""id"": ""e7ffc1b3-eea5-4fdf-8cf1-2a525fc958d2"",
            ""actions"": [
                {
                    ""name"": ""AbilityQ"",
                    ""type"": ""Button"",
                    ""id"": ""6b4a9c8a-c2ce-43b1-8cb9-ce913250eb74"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityW"",
                    ""type"": ""Button"",
                    ""id"": ""f59ce2b3-88d4-43ab-b2a1-80148b5311fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityE"",
                    ""type"": ""Button"",
                    ""id"": ""d6478da8-9847-497f-889f-65e75be80188"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityR"",
                    ""type"": ""Button"",
                    ""id"": ""177d6fd5-fd95-4132-b7c1-d6d9ac145cfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a8160698-b3db-447b-867a-b6cb647b163e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AbilityQ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a441af45-ab6e-478e-aa64-bdabf7a525ce"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbilityQ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c02df8c-e4cd-4dc5-91fe-383f5ac21ee3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AbilityW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""721ca5a8-438f-4b44-adc9-4bdd9aa25112"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbilityW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3faecdc8-3005-4cba-aae6-d0aef8fe5d9b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AbilityE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce170ac7-453c-4931-9869-1b7483c6204a"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbilityE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a501619-0e9e-43aa-b3ad-0e8acc0fbc28"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AbilityR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e26ab34-b33b-4cd9-89eb-fba071c1e052"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AbilityR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Driving"",
            ""id"": ""8bce64ad-3b02-4fb9-8d42-062180bf9c3a"",
            ""actions"": [
                {
                    ""name"": ""ThrottleForward"",
                    ""type"": ""Value"",
                    ""id"": ""caf3162e-6c0c-40c7-8ff8-0c0114345f9d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BrakeThrottleReverse"",
                    ""type"": ""Value"",
                    ""id"": ""544fe724-1dc4-4bc1-a685-ad936ae1c63b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SteeringAxis"",
                    ""type"": ""Value"",
                    ""id"": ""0d523890-f31e-4393-80fd-4be1f5cc31d6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7a2dc7be-4180-4c62-a847-14cdfb753cf0"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ThrottleForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8f48f25-128b-41f2-a657-a4be4bb135e8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""ThrottleForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""970cb6a1-0613-432c-8ecd-d223c6b17a03"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""BrakeThrottleReverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd0df2b1-97a9-41f3-b687-b29b4b55074e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""BrakeThrottleReverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e334bb20-02db-40d2-bf23-471b2a5363ff"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""SteeringAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""11856286-9f8f-49d3-b548-0527ecd51df3"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SteeringAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""8853d8af-9a2c-4bde-89d9-621d400e5d27"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""SteeringAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""be7c0318-1499-405f-b969-649da86151f8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""SteeringAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""14101762-0455-47c3-bdbb-75eb6f1e3b05"",
            ""actions"": [
                {
                    ""name"": ""InitiateZoom"",
                    ""type"": ""Button"",
                    ""id"": ""64f305dc-6fec-4496-a143-96c0acba67d4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5387418d-b297-4181-81b5-e0fc00c5d7d7"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""InitiateZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bff97dfd-ba9c-4804-ab1d-83879cf471f1"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""InitiateZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Object Interaction"",
            ""id"": ""925006cd-070b-487e-8ed7-20e8a9ad8b4d"",
            ""actions"": [
                {
                    ""name"": ""ObjectPickup"",
                    ""type"": ""Button"",
                    ""id"": ""75312bde-aeef-490e-9569-40df3c26c5c1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ObjectDrop"",
                    ""type"": ""Button"",
                    ""id"": ""7aacd8ac-efe0-48ae-9087-97dbbf8ee53c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""88b8494e-2001-4958-af2d-7afa084345b8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ObjectPickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d1b58b6-66c3-4629-81c3-0fd081ae2e26"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ObjectPickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc6291b1-b08b-4470-a1af-54150026df30"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ObjectDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcbbeeb6-3bc2-473e-a6e5-16910248e885"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ObjectDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Standard
            m_Standard = asset.FindActionMap("Standard", throwIfNotFound: true);
            m_Standard_LeftJoystickHorizontal = m_Standard.FindAction("LeftJoystickHorizontal", throwIfNotFound: true);
            m_Standard_LeftJoystickVertical = m_Standard.FindAction("LeftJoystickVertical", throwIfNotFound: true);
            m_Standard_RightJoystickHorizontal = m_Standard.FindAction("RightJoystickHorizontal", throwIfNotFound: true);
            m_Standard_RightJoystickVertical = m_Standard.FindAction("RightJoystickVertical", throwIfNotFound: true);
            m_Standard_LeftBumper = m_Standard.FindAction("LeftBumper", throwIfNotFound: true);
            m_Standard_RightBumper = m_Standard.FindAction("RightBumper", throwIfNotFound: true);
            m_Standard_CursorInput = m_Standard.FindAction("CursorInput", throwIfNotFound: true);
            m_Standard_Jump = m_Standard.FindAction("Jump", throwIfNotFound: true);
            m_Standard_Pause = m_Standard.FindAction("Pause", throwIfNotFound: true);
            m_Standard_Roll = m_Standard.FindAction("Roll", throwIfNotFound: true);
            m_Standard_Sprint = m_Standard.FindAction("Sprint", throwIfNotFound: true);
            m_Standard_Crouch = m_Standard.FindAction("Crouch", throwIfNotFound: true);
            m_Standard_Interact = m_Standard.FindAction("Interact", throwIfNotFound: true);
            // MOBA
            m_MOBA = asset.FindActionMap("MOBA", throwIfNotFound: true);
            m_MOBA_AbilityQ = m_MOBA.FindAction("AbilityQ", throwIfNotFound: true);
            m_MOBA_AbilityW = m_MOBA.FindAction("AbilityW", throwIfNotFound: true);
            m_MOBA_AbilityE = m_MOBA.FindAction("AbilityE", throwIfNotFound: true);
            m_MOBA_AbilityR = m_MOBA.FindAction("AbilityR", throwIfNotFound: true);
            // Driving
            m_Driving = asset.FindActionMap("Driving", throwIfNotFound: true);
            m_Driving_ThrottleForward = m_Driving.FindAction("ThrottleForward", throwIfNotFound: true);
            m_Driving_BrakeThrottleReverse = m_Driving.FindAction("BrakeThrottleReverse", throwIfNotFound: true);
            m_Driving_SteeringAxis = m_Driving.FindAction("SteeringAxis", throwIfNotFound: true);
            // Camera
            m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
            m_Camera_InitiateZoom = m_Camera.FindAction("InitiateZoom", throwIfNotFound: true);
            // Object Interaction
            m_ObjectInteraction = asset.FindActionMap("Object Interaction", throwIfNotFound: true);
            m_ObjectInteraction_ObjectPickup = m_ObjectInteraction.FindAction("ObjectPickup", throwIfNotFound: true);
            m_ObjectInteraction_ObjectDrop = m_ObjectInteraction.FindAction("ObjectDrop", throwIfNotFound: true);
        }

        ~@DefaultSwoleControls()
        {
            UnityEngine.Debug.Assert(!m_Standard.enabled, "This will cause a leak and performance issues, DefaultSwoleControls.Standard.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_MOBA.enabled, "This will cause a leak and performance issues, DefaultSwoleControls.MOBA.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Driving.enabled, "This will cause a leak and performance issues, DefaultSwoleControls.Driving.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Camera.enabled, "This will cause a leak and performance issues, DefaultSwoleControls.Camera.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_ObjectInteraction.enabled, "This will cause a leak and performance issues, DefaultSwoleControls.ObjectInteraction.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Standard
        private readonly InputActionMap m_Standard;
        private List<IStandardActions> m_StandardActionsCallbackInterfaces = new List<IStandardActions>();
        private readonly InputAction m_Standard_LeftJoystickHorizontal;
        private readonly InputAction m_Standard_LeftJoystickVertical;
        private readonly InputAction m_Standard_RightJoystickHorizontal;
        private readonly InputAction m_Standard_RightJoystickVertical;
        private readonly InputAction m_Standard_LeftBumper;
        private readonly InputAction m_Standard_RightBumper;
        private readonly InputAction m_Standard_CursorInput;
        private readonly InputAction m_Standard_Jump;
        private readonly InputAction m_Standard_Pause;
        private readonly InputAction m_Standard_Roll;
        private readonly InputAction m_Standard_Sprint;
        private readonly InputAction m_Standard_Crouch;
        private readonly InputAction m_Standard_Interact;
        /// <summary>
        /// Provides access to input actions defined in input action map "Standard".
        /// </summary>
        public struct StandardActions
        {
            private @DefaultSwoleControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public StandardActions(@DefaultSwoleControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Standard/LeftJoystickHorizontal".
            /// </summary>
            public InputAction @LeftJoystickHorizontal => m_Wrapper.m_Standard_LeftJoystickHorizontal;
            /// <summary>
            /// Provides access to the underlying input action "Standard/LeftJoystickVertical".
            /// </summary>
            public InputAction @LeftJoystickVertical => m_Wrapper.m_Standard_LeftJoystickVertical;
            /// <summary>
            /// Provides access to the underlying input action "Standard/RightJoystickHorizontal".
            /// </summary>
            public InputAction @RightJoystickHorizontal => m_Wrapper.m_Standard_RightJoystickHorizontal;
            /// <summary>
            /// Provides access to the underlying input action "Standard/RightJoystickVertical".
            /// </summary>
            public InputAction @RightJoystickVertical => m_Wrapper.m_Standard_RightJoystickVertical;
            /// <summary>
            /// Provides access to the underlying input action "Standard/LeftBumper".
            /// </summary>
            public InputAction @LeftBumper => m_Wrapper.m_Standard_LeftBumper;
            /// <summary>
            /// Provides access to the underlying input action "Standard/RightBumper".
            /// </summary>
            public InputAction @RightBumper => m_Wrapper.m_Standard_RightBumper;
            /// <summary>
            /// Provides access to the underlying input action "Standard/CursorInput".
            /// </summary>
            public InputAction @CursorInput => m_Wrapper.m_Standard_CursorInput;
            /// <summary>
            /// Provides access to the underlying input action "Standard/Jump".
            /// </summary>
            public InputAction @Jump => m_Wrapper.m_Standard_Jump;
            /// <summary>
            /// Provides access to the underlying input action "Standard/Pause".
            /// </summary>
            public InputAction @Pause => m_Wrapper.m_Standard_Pause;
            /// <summary>
            /// Provides access to the underlying input action "Standard/Roll".
            /// </summary>
            public InputAction @Roll => m_Wrapper.m_Standard_Roll;
            /// <summary>
            /// Provides access to the underlying input action "Standard/Sprint".
            /// </summary>
            public InputAction @Sprint => m_Wrapper.m_Standard_Sprint;
            /// <summary>
            /// Provides access to the underlying input action "Standard/Crouch".
            /// </summary>
            public InputAction @Crouch => m_Wrapper.m_Standard_Crouch;
            /// <summary>
            /// Provides access to the underlying input action "Standard/Interact".
            /// </summary>
            public InputAction @Interact => m_Wrapper.m_Standard_Interact;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Standard; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="StandardActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(StandardActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="StandardActions" />
            public void AddCallbacks(IStandardActions instance)
            {
                if (instance == null || m_Wrapper.m_StandardActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_StandardActionsCallbackInterfaces.Add(instance);
                @LeftJoystickHorizontal.started += instance.OnLeftJoystickHorizontal;
                @LeftJoystickHorizontal.performed += instance.OnLeftJoystickHorizontal;
                @LeftJoystickHorizontal.canceled += instance.OnLeftJoystickHorizontal;
                @LeftJoystickVertical.started += instance.OnLeftJoystickVertical;
                @LeftJoystickVertical.performed += instance.OnLeftJoystickVertical;
                @LeftJoystickVertical.canceled += instance.OnLeftJoystickVertical;
                @RightJoystickHorizontal.started += instance.OnRightJoystickHorizontal;
                @RightJoystickHorizontal.performed += instance.OnRightJoystickHorizontal;
                @RightJoystickHorizontal.canceled += instance.OnRightJoystickHorizontal;
                @RightJoystickVertical.started += instance.OnRightJoystickVertical;
                @RightJoystickVertical.performed += instance.OnRightJoystickVertical;
                @RightJoystickVertical.canceled += instance.OnRightJoystickVertical;
                @LeftBumper.started += instance.OnLeftBumper;
                @LeftBumper.performed += instance.OnLeftBumper;
                @LeftBumper.canceled += instance.OnLeftBumper;
                @RightBumper.started += instance.OnRightBumper;
                @RightBumper.performed += instance.OnRightBumper;
                @RightBumper.canceled += instance.OnRightBumper;
                @CursorInput.started += instance.OnCursorInput;
                @CursorInput.performed += instance.OnCursorInput;
                @CursorInput.canceled += instance.OnCursorInput;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Roll.started += instance.OnRoll;
                @Roll.performed += instance.OnRoll;
                @Roll.canceled += instance.OnRoll;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="StandardActions" />
            private void UnregisterCallbacks(IStandardActions instance)
            {
                @LeftJoystickHorizontal.started -= instance.OnLeftJoystickHorizontal;
                @LeftJoystickHorizontal.performed -= instance.OnLeftJoystickHorizontal;
                @LeftJoystickHorizontal.canceled -= instance.OnLeftJoystickHorizontal;
                @LeftJoystickVertical.started -= instance.OnLeftJoystickVertical;
                @LeftJoystickVertical.performed -= instance.OnLeftJoystickVertical;
                @LeftJoystickVertical.canceled -= instance.OnLeftJoystickVertical;
                @RightJoystickHorizontal.started -= instance.OnRightJoystickHorizontal;
                @RightJoystickHorizontal.performed -= instance.OnRightJoystickHorizontal;
                @RightJoystickHorizontal.canceled -= instance.OnRightJoystickHorizontal;
                @RightJoystickVertical.started -= instance.OnRightJoystickVertical;
                @RightJoystickVertical.performed -= instance.OnRightJoystickVertical;
                @RightJoystickVertical.canceled -= instance.OnRightJoystickVertical;
                @LeftBumper.started -= instance.OnLeftBumper;
                @LeftBumper.performed -= instance.OnLeftBumper;
                @LeftBumper.canceled -= instance.OnLeftBumper;
                @RightBumper.started -= instance.OnRightBumper;
                @RightBumper.performed -= instance.OnRightBumper;
                @RightBumper.canceled -= instance.OnRightBumper;
                @CursorInput.started -= instance.OnCursorInput;
                @CursorInput.performed -= instance.OnCursorInput;
                @CursorInput.canceled -= instance.OnCursorInput;
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
                @Pause.started -= instance.OnPause;
                @Pause.performed -= instance.OnPause;
                @Pause.canceled -= instance.OnPause;
                @Roll.started -= instance.OnRoll;
                @Roll.performed -= instance.OnRoll;
                @Roll.canceled -= instance.OnRoll;
                @Sprint.started -= instance.OnSprint;
                @Sprint.performed -= instance.OnSprint;
                @Sprint.canceled -= instance.OnSprint;
                @Crouch.started -= instance.OnCrouch;
                @Crouch.performed -= instance.OnCrouch;
                @Crouch.canceled -= instance.OnCrouch;
                @Interact.started -= instance.OnInteract;
                @Interact.performed -= instance.OnInteract;
                @Interact.canceled -= instance.OnInteract;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="StandardActions.UnregisterCallbacks(IStandardActions)" />.
            /// </summary>
            /// <seealso cref="StandardActions.UnregisterCallbacks(IStandardActions)" />
            public void RemoveCallbacks(IStandardActions instance)
            {
                if (m_Wrapper.m_StandardActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="StandardActions.AddCallbacks(IStandardActions)" />
            /// <seealso cref="StandardActions.RemoveCallbacks(IStandardActions)" />
            /// <seealso cref="StandardActions.UnregisterCallbacks(IStandardActions)" />
            public void SetCallbacks(IStandardActions instance)
            {
                foreach (var item in m_Wrapper.m_StandardActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_StandardActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="StandardActions" /> instance referencing this action map.
        /// </summary>
        public StandardActions @Standard => new StandardActions(this);

        // MOBA
        private readonly InputActionMap m_MOBA;
        private List<IMOBAActions> m_MOBAActionsCallbackInterfaces = new List<IMOBAActions>();
        private readonly InputAction m_MOBA_AbilityQ;
        private readonly InputAction m_MOBA_AbilityW;
        private readonly InputAction m_MOBA_AbilityE;
        private readonly InputAction m_MOBA_AbilityR;
        /// <summary>
        /// Provides access to input actions defined in input action map "MOBA".
        /// </summary>
        public struct MOBAActions
        {
            private @DefaultSwoleControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public MOBAActions(@DefaultSwoleControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "MOBA/AbilityQ".
            /// </summary>
            public InputAction @AbilityQ => m_Wrapper.m_MOBA_AbilityQ;
            /// <summary>
            /// Provides access to the underlying input action "MOBA/AbilityW".
            /// </summary>
            public InputAction @AbilityW => m_Wrapper.m_MOBA_AbilityW;
            /// <summary>
            /// Provides access to the underlying input action "MOBA/AbilityE".
            /// </summary>
            public InputAction @AbilityE => m_Wrapper.m_MOBA_AbilityE;
            /// <summary>
            /// Provides access to the underlying input action "MOBA/AbilityR".
            /// </summary>
            public InputAction @AbilityR => m_Wrapper.m_MOBA_AbilityR;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_MOBA; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="MOBAActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(MOBAActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="MOBAActions" />
            public void AddCallbacks(IMOBAActions instance)
            {
                if (instance == null || m_Wrapper.m_MOBAActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MOBAActionsCallbackInterfaces.Add(instance);
                @AbilityQ.started += instance.OnAbilityQ;
                @AbilityQ.performed += instance.OnAbilityQ;
                @AbilityQ.canceled += instance.OnAbilityQ;
                @AbilityW.started += instance.OnAbilityW;
                @AbilityW.performed += instance.OnAbilityW;
                @AbilityW.canceled += instance.OnAbilityW;
                @AbilityE.started += instance.OnAbilityE;
                @AbilityE.performed += instance.OnAbilityE;
                @AbilityE.canceled += instance.OnAbilityE;
                @AbilityR.started += instance.OnAbilityR;
                @AbilityR.performed += instance.OnAbilityR;
                @AbilityR.canceled += instance.OnAbilityR;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="MOBAActions" />
            private void UnregisterCallbacks(IMOBAActions instance)
            {
                @AbilityQ.started -= instance.OnAbilityQ;
                @AbilityQ.performed -= instance.OnAbilityQ;
                @AbilityQ.canceled -= instance.OnAbilityQ;
                @AbilityW.started -= instance.OnAbilityW;
                @AbilityW.performed -= instance.OnAbilityW;
                @AbilityW.canceled -= instance.OnAbilityW;
                @AbilityE.started -= instance.OnAbilityE;
                @AbilityE.performed -= instance.OnAbilityE;
                @AbilityE.canceled -= instance.OnAbilityE;
                @AbilityR.started -= instance.OnAbilityR;
                @AbilityR.performed -= instance.OnAbilityR;
                @AbilityR.canceled -= instance.OnAbilityR;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MOBAActions.UnregisterCallbacks(IMOBAActions)" />.
            /// </summary>
            /// <seealso cref="MOBAActions.UnregisterCallbacks(IMOBAActions)" />
            public void RemoveCallbacks(IMOBAActions instance)
            {
                if (m_Wrapper.m_MOBAActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="MOBAActions.AddCallbacks(IMOBAActions)" />
            /// <seealso cref="MOBAActions.RemoveCallbacks(IMOBAActions)" />
            /// <seealso cref="MOBAActions.UnregisterCallbacks(IMOBAActions)" />
            public void SetCallbacks(IMOBAActions instance)
            {
                foreach (var item in m_Wrapper.m_MOBAActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MOBAActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="MOBAActions" /> instance referencing this action map.
        /// </summary>
        public MOBAActions @MOBA => new MOBAActions(this);

        // Driving
        private readonly InputActionMap m_Driving;
        private List<IDrivingActions> m_DrivingActionsCallbackInterfaces = new List<IDrivingActions>();
        private readonly InputAction m_Driving_ThrottleForward;
        private readonly InputAction m_Driving_BrakeThrottleReverse;
        private readonly InputAction m_Driving_SteeringAxis;
        /// <summary>
        /// Provides access to input actions defined in input action map "Driving".
        /// </summary>
        public struct DrivingActions
        {
            private @DefaultSwoleControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public DrivingActions(@DefaultSwoleControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Driving/ThrottleForward".
            /// </summary>
            public InputAction @ThrottleForward => m_Wrapper.m_Driving_ThrottleForward;
            /// <summary>
            /// Provides access to the underlying input action "Driving/BrakeThrottleReverse".
            /// </summary>
            public InputAction @BrakeThrottleReverse => m_Wrapper.m_Driving_BrakeThrottleReverse;
            /// <summary>
            /// Provides access to the underlying input action "Driving/SteeringAxis".
            /// </summary>
            public InputAction @SteeringAxis => m_Wrapper.m_Driving_SteeringAxis;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Driving; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="DrivingActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(DrivingActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="DrivingActions" />
            public void AddCallbacks(IDrivingActions instance)
            {
                if (instance == null || m_Wrapper.m_DrivingActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_DrivingActionsCallbackInterfaces.Add(instance);
                @ThrottleForward.started += instance.OnThrottleForward;
                @ThrottleForward.performed += instance.OnThrottleForward;
                @ThrottleForward.canceled += instance.OnThrottleForward;
                @BrakeThrottleReverse.started += instance.OnBrakeThrottleReverse;
                @BrakeThrottleReverse.performed += instance.OnBrakeThrottleReverse;
                @BrakeThrottleReverse.canceled += instance.OnBrakeThrottleReverse;
                @SteeringAxis.started += instance.OnSteeringAxis;
                @SteeringAxis.performed += instance.OnSteeringAxis;
                @SteeringAxis.canceled += instance.OnSteeringAxis;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="DrivingActions" />
            private void UnregisterCallbacks(IDrivingActions instance)
            {
                @ThrottleForward.started -= instance.OnThrottleForward;
                @ThrottleForward.performed -= instance.OnThrottleForward;
                @ThrottleForward.canceled -= instance.OnThrottleForward;
                @BrakeThrottleReverse.started -= instance.OnBrakeThrottleReverse;
                @BrakeThrottleReverse.performed -= instance.OnBrakeThrottleReverse;
                @BrakeThrottleReverse.canceled -= instance.OnBrakeThrottleReverse;
                @SteeringAxis.started -= instance.OnSteeringAxis;
                @SteeringAxis.performed -= instance.OnSteeringAxis;
                @SteeringAxis.canceled -= instance.OnSteeringAxis;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DrivingActions.UnregisterCallbacks(IDrivingActions)" />.
            /// </summary>
            /// <seealso cref="DrivingActions.UnregisterCallbacks(IDrivingActions)" />
            public void RemoveCallbacks(IDrivingActions instance)
            {
                if (m_Wrapper.m_DrivingActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="DrivingActions.AddCallbacks(IDrivingActions)" />
            /// <seealso cref="DrivingActions.RemoveCallbacks(IDrivingActions)" />
            /// <seealso cref="DrivingActions.UnregisterCallbacks(IDrivingActions)" />
            public void SetCallbacks(IDrivingActions instance)
            {
                foreach (var item in m_Wrapper.m_DrivingActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_DrivingActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="DrivingActions" /> instance referencing this action map.
        /// </summary>
        public DrivingActions @Driving => new DrivingActions(this);

        // Camera
        private readonly InputActionMap m_Camera;
        private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
        private readonly InputAction m_Camera_InitiateZoom;
        /// <summary>
        /// Provides access to input actions defined in input action map "Camera".
        /// </summary>
        public struct CameraActions
        {
            private @DefaultSwoleControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public CameraActions(@DefaultSwoleControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Camera/InitiateZoom".
            /// </summary>
            public InputAction @InitiateZoom => m_Wrapper.m_Camera_InitiateZoom;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Camera; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="CameraActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="CameraActions" />
            public void AddCallbacks(ICameraActions instance)
            {
                if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
                @InitiateZoom.started += instance.OnInitiateZoom;
                @InitiateZoom.performed += instance.OnInitiateZoom;
                @InitiateZoom.canceled += instance.OnInitiateZoom;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="CameraActions" />
            private void UnregisterCallbacks(ICameraActions instance)
            {
                @InitiateZoom.started -= instance.OnInitiateZoom;
                @InitiateZoom.performed -= instance.OnInitiateZoom;
                @InitiateZoom.canceled -= instance.OnInitiateZoom;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CameraActions.UnregisterCallbacks(ICameraActions)" />.
            /// </summary>
            /// <seealso cref="CameraActions.UnregisterCallbacks(ICameraActions)" />
            public void RemoveCallbacks(ICameraActions instance)
            {
                if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="CameraActions.AddCallbacks(ICameraActions)" />
            /// <seealso cref="CameraActions.RemoveCallbacks(ICameraActions)" />
            /// <seealso cref="CameraActions.UnregisterCallbacks(ICameraActions)" />
            public void SetCallbacks(ICameraActions instance)
            {
                foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="CameraActions" /> instance referencing this action map.
        /// </summary>
        public CameraActions @Camera => new CameraActions(this);

        // Object Interaction
        private readonly InputActionMap m_ObjectInteraction;
        private List<IObjectInteractionActions> m_ObjectInteractionActionsCallbackInterfaces = new List<IObjectInteractionActions>();
        private readonly InputAction m_ObjectInteraction_ObjectPickup;
        private readonly InputAction m_ObjectInteraction_ObjectDrop;
        /// <summary>
        /// Provides access to input actions defined in input action map "Object Interaction".
        /// </summary>
        public struct ObjectInteractionActions
        {
            private @DefaultSwoleControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public ObjectInteractionActions(@DefaultSwoleControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "ObjectInteraction/ObjectPickup".
            /// </summary>
            public InputAction @ObjectPickup => m_Wrapper.m_ObjectInteraction_ObjectPickup;
            /// <summary>
            /// Provides access to the underlying input action "ObjectInteraction/ObjectDrop".
            /// </summary>
            public InputAction @ObjectDrop => m_Wrapper.m_ObjectInteraction_ObjectDrop;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_ObjectInteraction; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="ObjectInteractionActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(ObjectInteractionActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="ObjectInteractionActions" />
            public void AddCallbacks(IObjectInteractionActions instance)
            {
                if (instance == null || m_Wrapper.m_ObjectInteractionActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_ObjectInteractionActionsCallbackInterfaces.Add(instance);
                @ObjectPickup.started += instance.OnObjectPickup;
                @ObjectPickup.performed += instance.OnObjectPickup;
                @ObjectPickup.canceled += instance.OnObjectPickup;
                @ObjectDrop.started += instance.OnObjectDrop;
                @ObjectDrop.performed += instance.OnObjectDrop;
                @ObjectDrop.canceled += instance.OnObjectDrop;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="ObjectInteractionActions" />
            private void UnregisterCallbacks(IObjectInteractionActions instance)
            {
                @ObjectPickup.started -= instance.OnObjectPickup;
                @ObjectPickup.performed -= instance.OnObjectPickup;
                @ObjectPickup.canceled -= instance.OnObjectPickup;
                @ObjectDrop.started -= instance.OnObjectDrop;
                @ObjectDrop.performed -= instance.OnObjectDrop;
                @ObjectDrop.canceled -= instance.OnObjectDrop;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ObjectInteractionActions.UnregisterCallbacks(IObjectInteractionActions)" />.
            /// </summary>
            /// <seealso cref="ObjectInteractionActions.UnregisterCallbacks(IObjectInteractionActions)" />
            public void RemoveCallbacks(IObjectInteractionActions instance)
            {
                if (m_Wrapper.m_ObjectInteractionActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="ObjectInteractionActions.AddCallbacks(IObjectInteractionActions)" />
            /// <seealso cref="ObjectInteractionActions.RemoveCallbacks(IObjectInteractionActions)" />
            /// <seealso cref="ObjectInteractionActions.UnregisterCallbacks(IObjectInteractionActions)" />
            public void SetCallbacks(IObjectInteractionActions instance)
            {
                foreach (var item in m_Wrapper.m_ObjectInteractionActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_ObjectInteractionActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="ObjectInteractionActions" /> instance referencing this action map.
        /// </summary>
        public ObjectInteractionActions @ObjectInteraction => new ObjectInteractionActions(this);
        private int m_KeyboardSchemeIndex = -1;
        /// <summary>
        /// Provides access to the input control scheme.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
        public InputControlScheme KeyboardScheme
        {
            get
            {
                if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
                return asset.controlSchemes[m_KeyboardSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        /// <summary>
        /// Provides access to the input control scheme.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Standard" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="StandardActions.AddCallbacks(IStandardActions)" />
        /// <seealso cref="StandardActions.RemoveCallbacks(IStandardActions)" />
        public interface IStandardActions
        {
            /// <summary>
            /// Method invoked when associated input action "LeftJoystickHorizontal" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftJoystickHorizontal(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LeftJoystickVertical" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftJoystickVertical(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightJoystickHorizontal" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightJoystickHorizontal(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightJoystickVertical" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightJoystickVertical(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LeftBumper" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftBumper(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightBumper" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightBumper(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "CursorInput" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCursorInput(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnJump(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPause(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Roll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRoll(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Sprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSprint(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Crouch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCrouch(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Interact" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnInteract(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MOBA" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="MOBAActions.AddCallbacks(IMOBAActions)" />
        /// <seealso cref="MOBAActions.RemoveCallbacks(IMOBAActions)" />
        public interface IMOBAActions
        {
            /// <summary>
            /// Method invoked when associated input action "AbilityQ" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAbilityQ(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "AbilityW" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAbilityW(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "AbilityE" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAbilityE(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "AbilityR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAbilityR(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Driving" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="DrivingActions.AddCallbacks(IDrivingActions)" />
        /// <seealso cref="DrivingActions.RemoveCallbacks(IDrivingActions)" />
        public interface IDrivingActions
        {
            /// <summary>
            /// Method invoked when associated input action "ThrottleForward" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnThrottleForward(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "BrakeThrottleReverse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBrakeThrottleReverse(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SteeringAxis" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSteeringAxis(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Camera" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="CameraActions.AddCallbacks(ICameraActions)" />
        /// <seealso cref="CameraActions.RemoveCallbacks(ICameraActions)" />
        public interface ICameraActions
        {
            /// <summary>
            /// Method invoked when associated input action "InitiateZoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnInitiateZoom(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Object Interaction" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="ObjectInteractionActions.AddCallbacks(IObjectInteractionActions)" />
        /// <seealso cref="ObjectInteractionActions.RemoveCallbacks(IObjectInteractionActions)" />
        public interface IObjectInteractionActions
        {
            /// <summary>
            /// Method invoked when associated input action "ObjectPickup" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnObjectPickup(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ObjectDrop" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnObjectDrop(InputAction.CallbackContext context);
        }
    }
}
